exports.StockDatabase = [
{Name:"3i Infrastructure", BBTicker: "IN", OtasID: "OT.IN.S"},
{Name:"AA", BBTicker: "AA", OtasID: "OT.AA.S"},
{Name:"Anglo American", BBTicker: "AAL", OtasID: "OT.AAL.S"},
{Name:"Associated British Foods", BBTicker: "ABF", OtasID: "OT.ABF.S"},
{Name:"Acacia Mining", BBTicker: "ACA", OtasID: "OT.ACA.S"},
{Name:"Admiral Group", BBTicker: "ADM", OtasID: "OT.ADM.S"},
{Name:"Aggreko", BBTicker: "AGK", OtasID: "OT.AGK.S"},
{Name:"Assura Group", BBTicker: "AGR", OtasID: "OT.AGR.S"},
{Name:"Ashtead Group", BBTicker: "AHT", OtasID: "OT.AHT.S"},
{Name:"Aldermore Group", BBTicker: "ALD", OtasID: "OT.ALD.S"},
{Name:"Amec Foster Wheeler", BBTicker: "AMFW", OtasID: "OT.AMFW.S"},
{Name:"Antofagasta", BBTicker: "ANTO", OtasID: "OT.ANTO.S"},
{Name:"Ascential", BBTicker: "ASCL", OtasID: "OT.ASCL.S"},
{Name:"Ashmore Group", BBTicker: "ASHM", OtasID: "OT.ASHM.S"},
{Name:"Aberforth Smaller Companies Trust", BBTicker: "ASL", OtasID: "OT.ASL.S"},
{Name:"Alliance Trust", BBTicker: "ATST", OtasID: "OT.ATST.S"},
{Name:"Auto Trader Group", BBTicker: "AUTO", OtasID: "OT.AUTO.S"},
{Name:"Aviva", BBTicker: "AV", OtasID: "OT.AV.S"},
{Name:"AVEVA Group", BBTicker: "AVV", OtasID: "OT.AVV.S"},
{Name:"AstraZeneca", BBTicker: "AZN", OtasID: "OT.AZN.S"},
{Name:"BAE Systems", BBTicker: "BA", OtasID: "OT.BA.S"},
{Name:"Babcock International Group", BBTicker: "BAB", OtasID: "OT.BAB.S"},
{Name:"Barr A G", BBTicker: "BAG", OtasID: "OT.BAG.S"},
{Name:"Barclays", BBTicker: "BARC", OtasID: "OT.BARC.S"},
{Name:"British American Tobacco", BBTicker: "BATS", OtasID: "OT.BATS.S"},
{Name:"BBA Aviation", BBTicker: "BBA", OtasID: "OT.BBA.S"},
{Name:"Tritax Big Box Reit", BBTicker: "BBOX", OtasID: "OT.BBOX.S"},
{Name:"Balfour Beatty", BBTicker: "BBY", OtasID: "OT.BBY.S"},
{Name:"Barratt Developments", BBTicker: "BDEV", OtasID: "OT.BDEV.S"},
{Name:"Beazley", BBTicker: "BEZ", OtasID: "OT.BEZ.S"},
{Name:"BGEO Group", BBTicker: "BGEO", OtasID: "OT.BGEO.S"},
{Name:"Berkeley Group Holdings The", BBTicker: "BKG", OtasID: "OT.BKG.S"},
{Name:"British Land Co", BBTicker: "BLND", OtasID: "OT.BLND.S"},
{Name:"BHP Billiton", BBTicker: "BLT", OtasID: "OT.BLT.S"},
{Name:"B&M European Value Retail", BBTicker: "BME", OtasID: "OT.BME.S"},
{Name:"Bankers' Investment Trust the", BBTicker: "BNKR", OtasID: "OT.BNKR.S"},
{Name:"Bunzl", BBTicker: "BNZL", OtasID: "OT.BNZL.S"},
{Name:"Booker Group", BBTicker: "BOK", OtasID: "OT.BOK.S"},
{Name:"Bodycote", BBTicker: "BOY", OtasID: "OT.BOY.S"},
{Name:"BP", BBTicker: "BP", OtasID: "OT.BP.S"},
{Name:"Burberry Group", BBTicker: "BRBY", OtasID: "OT.BRBY.S"},
{Name:"Berendsen", BBTicker: "BRSN", OtasID: "OT.BRSN.S"},
{Name:"Brewin Dolphin Holdings", BBTicker: "BRW", OtasID: "OT.BRW.S"},
{Name:"BT Group", BBTicker: "BTA", OtasID: "OT.BTA.S"},
{Name:"British Empire Securities & General Trust", BBTicker: "BTEM", OtasID: "OT.BTEM.S"},
{Name:"BTG", BBTicker: "BTG", OtasID: "OT.BTG.S"},
{Name:"Britvic", BBTicker: "BVIC", OtasID: "OT.BVIC.S"},
{Name:"Bovis Homes Group", BBTicker: "BVS", OtasID: "OT.BVS.S"},
{Name:"Brown N Group", BBTicker: "BWNG", OtasID: "OT.BWNG.S"},
{Name:"Bellway", BBTicker: "BWY", OtasID: "OT.BWY.S"},
{Name:"Big Yellow Group", BBTicker: "BYG", OtasID: "OT.BYG.S"},
{Name:"Capital & Counties Properties", BBTicker: "CAPC", OtasID: "OT.CAPC.S"},
{Name:"Card Factory", BBTicker: "CARD", OtasID: "OT.CARD.S"},
{Name:"Close Brothers Group", BBTicker: "CBG", OtasID: "OT.CBG.S"},
{Name:"Computacenter", BBTicker: "CCC", OtasID: "OT.CCC.S"},
{Name:"Coca-Cola HBC", BBTicker: "CCH", OtasID: "OT.CCH.S"},
{Name:"Carnival", BBTicker: "CCL", OtasID: "OT.CCL.S"},
{Name:"Centamin", BBTicker: "CEY", OtasID: "OT.CEY.S"},
{Name:"Jimmy Choo", BBTicker: "CHOO", OtasID: "OT.CHOO.S"},
{Name:"Cineworld Group", BBTicker: "CINE", OtasID: "OT.CINE.S"},
{Name:"Clarkson", BBTicker: "CKN", OtasID: "OT.CKN.S"},
{Name:"Caledonia Investments", BBTicker: "CLDN", OtasID: "OT.CLDN.S"},
{Name:"CLS Holdings", BBTicker: "CLI", OtasID: "OT.CLI.S"},
{Name:"Carillion", BBTicker: "CLLN", OtasID: "OT.CLLN.S"},
{Name:"Centrica", BBTicker: "CNA", OtasID: "OT.CNA.S"},
{Name:"Cairn Energy", BBTicker: "CNE", OtasID: "OT.CNE.S"},
{Name:"Coats Group", BBTicker: "COA", OtasID: "OT.COA.S"},
{Name:"Cobham", BBTicker: "COB", OtasID: "OT.COB.S"},
{Name:"Compass Group", BBTicker: "CPG", OtasID: "OT.CPG.S"},
{Name:"Capita Group The", BBTicker: "CPI", OtasID: "OT.CPI.S"},
{Name:"Croda International", BBTicker: "CRDA", OtasID: "OT.CRDA.S"},
{Name:"CRH", BBTicker: "CRH", OtasID: "OT.CRH.S"},
{Name:"Crest Nicholson Holdings", BBTicker: "CRST", OtasID: "OT.CRST.S"},
{Name:"Countryside Properties", BBTicker: "CSP", OtasID: "OT.CSP.S"},
{Name:"ConvaTec Group", BBTicker: "CTEC", OtasID: "OT.CTEC.S"},
{Name:"City Of London Investment Trust the", BBTicker: "CTY", OtasID: "OT.CTY.S"},
{Name:"Cranswick", BBTicker: "CWK", OtasID: "OT.CWK.S"},
{Name:"CYBG", BBTicker: "CYBG", OtasID: "OT.CYBG.S"},
{Name:"Dixons Carphone", BBTicker: "DC", OtasID: "OT.DC.S"},
{Name:"DCC", BBTicker: "DCC", OtasID: "OT.DCC.S"},
{Name:"Dairy Crest Group", BBTicker: "DCG", OtasID: "OT.DCG.S"},
{Name:"Diageo", BBTicker: "DGE", OtasID: "OT.DGE.S"},
{Name:"Daejan Holdings", BBTicker: "DJAN", OtasID: "OT.DJAN.S"},
{Name:"Direct Line Insurance Group", BBTicker: "DLG", OtasID: "OT.DLG.S"},
{Name:"Derwent London", BBTicker: "DLN", OtasID: "OT.DLN.S"},
{Name:"Dunelm Group", BBTicker: "DNLM", OtasID: "OT.DNLM.S"},
{Name:"Domino's Pizza Group", BBTicker: "DOM", OtasID: "OT.DOM.S"},
{Name:"Dechra Pharmaceuticals", BBTicker: "DPH", OtasID: "OT.DPH.S"},
{Name:"Diploma", BBTicker: "DPLM", OtasID: "OT.DPLM.S"},
{Name:"Drax Group", BBTicker: "DRX", OtasID: "OT.DRX.S"},
{Name:"Dignity", BBTicker: "DTY", OtasID: "OT.DTY.S"},
{Name:"Electrocomponents", BBTicker: "ECM", OtasID: "OT.ECM.S"},
{Name:"Edinburgh Investment Trust the", BBTicker: "EDIN", OtasID: "OT.EDIN.S"},
{Name:"Elementis", BBTicker: "ELM", OtasID: "OT.ELM.S"},
{Name:"Electra Private Equity", BBTicker: "ELTA", OtasID: "OT.ELTA.S"},
{Name:"Man Group", BBTicker: "EMG", OtasID: "OT.EMG.S"},
{Name:"Euromoney Institutional Investor", BBTicker: "ERM", OtasID: "OT.ERM.S"},
{Name:"Essentra", BBTicker: "ESNT", OtasID: "OT.ESNT.S"},
{Name:"esure Group", BBTicker: "ESUR", OtasID: "OT.ESUR.S"},
{Name:"Entertainment One Group", BBTicker: "ETO", OtasID: "OT.ETO.S"},
{Name:"Evraz", BBTicker: "EVR", OtasID: "OT.EVR.S"},
{Name:"Experian", BBTicker: "EXPN", OtasID: "OT.EXPN.S"},
{Name:"easyJet", BBTicker: "EZJ", OtasID: "OT.EZJ.S"},
{Name:"F&C Commercial Property Tst Ld", BBTicker: "FCPT", OtasID: "OT.FCPT.S"},
{Name:"Fidelity China Special Situations", BBTicker: "FCSS", OtasID: "OT.FCSS.S"},
{Name:"FDM Group Holdings", BBTicker: "FDM", OtasID: "OT.FDM.S"},
{Name:"Fidessa Group", BBTicker: "FDSA", OtasID: "OT.FDSA.S"},
{Name:"Ferguson Ord 10 5366p", BBTicker: "FERG", OtasID: "OT.FERG.S"},
{Name:"Fidelity European Values", BBTicker: "FEV", OtasID: "OT.FEV.S"},
{Name:"FirstGroup", BBTicker: "FGP", OtasID: "OT.FGP.S"},
{Name:"Finsbury Growth & Income Trust", BBTicker: "FGT", OtasID: "OT.FGT.S"},
{Name:"Foreign & Colonial Investment Trust", BBTicker: "FRCL", OtasID: "OT.FRCL.S"},
{Name:"Fresnillo", BBTicker: "FRES", OtasID: "OT.FRES.S"},
{Name:"Fisher James & Sons", BBTicker: "FSJ", OtasID: "OT.FSJ.S"},
{Name:"Ferrexpo", BBTicker: "FXPO", OtasID: "OT.FXPO.S"},
{Name:"GCP Infrastructure Investments", BBTicker: "GCP", OtasID: "OT.GCP.S"},
{Name:"Galliford Try", BBTicker: "GFRD", OtasID: "OT.GFRD.S"},
{Name:"G4S", BBTicker: "GFS", OtasID: "OT.GFS.S"},
{Name:"Grafton Group", BBTicker: "GFTU", OtasID: "OT.GFTU.S"},
{Name:"GKN", BBTicker: "GKN", OtasID: "OT.GKN.S"},
{Name:"Glencore", BBTicker: "GLEN", OtasID: "OT.GLEN.S"},
{Name:"Greencore Group", BBTicker: "GNC", OtasID: "OT.GNC.S"},
{Name:"Greene King", BBTicker: "GNK", OtasID: "OT.GNK.S"},
{Name:"Genus", BBTicker: "GNS", OtasID: "OT.GNS.S"},
{Name:"Go-Ahead Group The", BBTicker: "GOG", OtasID: "OT.GOG.S"},
{Name:"Great Portland Estates", BBTicker: "GPOR", OtasID: "OT.GPOR.S"},
{Name:"Greggs", BBTicker: "GRG", OtasID: "OT.GRG.S"},
{Name:"Grainger", BBTicker: "GRI", OtasID: "OT.GRI.S"},
{Name:"GlaxoSmithKline", BBTicker: "GSK", OtasID: "OT.GSK.S"},
{Name:"Genesis Emerging Markets Fnd Ld", BBTicker: "GSS", OtasID: "OT.GSS.S"},
{Name:"GVC Holdings", BBTicker: "GVC", OtasID: "OT.GVC.S"},
{Name:"Hays", BBTicker: "HAS", OtasID: "OT.HAS.S"},
{Name:"Halfords Group", BBTicker: "HFD", OtasID: "OT.HFD.S"},
{Name:"HICL Infrastructure Co", BBTicker: "HICL", OtasID: "OT.HICL.S"},
{Name:"Hikma Pharmaceuticals", BBTicker: "HIK", OtasID: "OT.HIK.S"},
{Name:"Hill & Smith Holdings", BBTicker: "HILS", OtasID: "OT.HILS.S"},
{Name:"Hargreaves Lansdown", BBTicker: "HL", OtasID: "OT.HL.S"},
{Name:"Halma", BBTicker: "HLMA", OtasID: "OT.HLMA.S"},
{Name:"Hammerson", BBTicker: "HMSO", OtasID: "OT.HMSO.S"},
{Name:"Hochschild Mining", BBTicker: "HOC", OtasID: "OT.HOC.S"},
{Name:"HSBC Holdings", BBTicker: "HSBA", OtasID: "OT.HSBA.S"},
{Name:"Hastings Group Holdings", BBTicker: "HSTG", OtasID: "OT.HSTG.S"},
{Name:"Hansteen Holdings", BBTicker: "HSTN", OtasID: "OT.HSTN.S"},
{Name:"Homeserve", BBTicker: "HSV", OtasID: "OT.HSV.S"},
{Name:"Hiscox", BBTicker: "HSX", OtasID: "OT.HSX.S"},
{Name:"Hunting", BBTicker: "HTG", OtasID: "OT.HTG.S"},
{Name:"Harbourvest Global Private Equity", BBTicker: "HVPE", OtasID: "OT.HVPE.S"},
{Name:"Howden Joinery Group", BBTicker: "HWDN", OtasID: "OT.HWDN.S"},
{Name:"International Consolidated Airlines Group", BBTicker: "IAG", OtasID: "OT.IAG.S"},
{Name:"Ibstock", BBTicker: "IBST", OtasID: "OT.IBST.S"},
{Name:"Intermediate Capital Group", BBTicker: "ICP", OtasID: "OT.ICP.S"},
{Name:"IG Group Holdings", BBTicker: "IGG", OtasID: "OT.IGG.S"},
{Name:"InterContinental Hotels Group", BBTicker: "IHG", OtasID: "OT.IHG.S"},
{Name:"3i Group", BBTicker: "III", OtasID: "OT.III.S"},
{Name:"Imperial Brands", BBTicker: "IMB", OtasID: "OT.IMB.S"},
{Name:"IMI", BBTicker: "IMI", OtasID: "OT.IMI.S"},
{Name:"Inchcape", BBTicker: "INCH", OtasID: "OT.INCH.S"},
{Name:"Indivior", BBTicker: "INDV", OtasID: "OT.INDV.S"},
{Name:"Informa", BBTicker: "INF", OtasID: "OT.INF.S"},
{Name:"International Public Partnership", BBTicker: "INPP", OtasID: "OT.INPP.S"},
{Name:"Intu Properties", BBTicker: "INTU", OtasID: "OT.INTU.S"},
{Name:"Investec", BBTicker: "INVP", OtasID: "OT.INVP.S"},
{Name:"IP Group", BBTicker: "IPO", OtasID: "OT.IPO.S"},
{Name:"Inmarsat", BBTicker: "ISAT", OtasID: "OT.ISAT.S"},
{Name:"Intertek Group", BBTicker: "ITRK", OtasID: "OT.ITRK.S"},
{Name:"ITV", BBTicker: "ITV", OtasID: "OT.ITV.S"},
{Name:"IWG", BBTicker: "IWG", OtasID: "OT.IWG.S"},
{Name:"JPMorgan American IT", BBTicker: "JAM", OtasID: "OT.JAM.S"},
{Name:"JD Sports Fashion", BBTicker: "JD", OtasID: "OT.JD.S"},
{Name:"Wetherspoon J D", BBTicker: "JDW", OtasID: "OT.JDW.S"},
{Name:"Just Eat", BBTicker: "JE", OtasID: "OT.JE.S"},
{Name:"JPMorgan Indian Investment Trust", BBTicker: "JII", OtasID: "OT.JII.S"},
{Name:"John Laing Group", BBTicker: "JLG", OtasID: "OT.JLG.S"},
{Name:"John Laing Infrastructure Fund", BBTicker: "JLIF", OtasID: "OT.JLIF.S"},
{Name:"Jardine Lloyd Thompson Group", BBTicker: "JLT", OtasID: "OT.JLT.S"},
{Name:"Johnson Matthey", BBTicker: "JMAT", OtasID: "OT.JMAT.S"},
{Name:"JPMorgan Emerging Markets Investment Trust", BBTicker: "JMG", OtasID: "OT.JMG.S"},
{Name:"Jupiter Fund Management", BBTicker: "JUP", OtasID: "OT.JUP.S"},
{Name:"Just Group Ord 10p", BBTicker: "JUST", OtasID: "OT.JUST.S"},
{Name:"Kaz Minerals", BBTicker: "KAZ", OtasID: "OT.KAZ.S"},
{Name:"Kingfisher", BBTicker: "KGF", OtasID: "OT.KGF.S"},
{Name:"Kier Group", BBTicker: "KIE", OtasID: "OT.KIE.S"},
{Name:"Kennedy Wilson Europe Real Estate", BBTicker: "KWE", OtasID: "OT.KWE.S"},
{Name:"Land Securities Group", BBTicker: "LAND", OtasID: "OT.LAND.S"},
{Name:"Ladbrokes Coral Group", BBTicker: "LCL", OtasID: "OT.LCL.S"},
{Name:"Legal & General Group", BBTicker: "LGEN", OtasID: "OT.LGEN.S"},
{Name:"Lloyds Banking Group ORD", BBTicker: "LLOY", OtasID: "OT.LLOY.S"},
{Name:"LondonMetric Property", BBTicker: "LMP", OtasID: "OT.LMP.S"},
{Name:"Lancashire Holdings", BBTicker: "LRE", OtasID: "OT.LRE.S"},
{Name:"London Stock Exchange Group", BBTicker: "LSE", OtasID: "OT.LSE.S"},
{Name:"Mitchells & Butlers", BBTicker: "MAB", OtasID: "OT.MAB.S"},
{Name:"Marston's", BBTicker: "MARS", OtasID: "OT.MARS.S"},
{Name:"Micro Focus International", BBTicker: "MCRO", OtasID: "OT.MCRO.S"},
{Name:"Mccarthy Stone", BBTicker: "MCS", OtasID: "OT.MCS.S"},
{Name:"Mediclinic International", BBTicker: "MDC", OtasID: "OT.MDC.S"},
{Name:"Merlin Entertainments", BBTicker: "MERL", OtasID: "OT.MERL.S"},
{Name:"Morgan Advanced Materials", BBTicker: "MGAM", OtasID: "OT.MGAM.S"},
{Name:"Meggitt", BBTicker: "MGGT", OtasID: "OT.MGGT.S"},
{Name:"Marks & Spencer Group", BBTicker: "MKS", OtasID: "OT.MKS.S"},
{Name:"Millennium & Copthorne Hotels", BBTicker: "MLC", OtasID: "OT.MLC.S"},
{Name:"Mondi", BBTicker: "MNDI", OtasID: "OT.MNDI.S"},
{Name:"Monks Investment Trust the", BBTicker: "MNKS", OtasID: "OT.MNKS.S"},
{Name:"Moneysupermarket.com Group", BBTicker: "MONY", OtasID: "OT.MONY.S"},
{Name:"Mercantile Inv Tst", BBTicker: "MRC", OtasID: "OT.MRC.S"},
{Name:"Melrose", BBTicker: "MRO", OtasID: "OT.MRO.S"},
{Name:"Morrison Wm Supermarkets", BBTicker: "MRW", OtasID: "OT.MRW.S"},
{Name:"Marshalls", BBTicker: "MSLH", OtasID: "OT.MSLH.S"},
{Name:"MITIE Group", BBTicker: "MTO", OtasID: "OT.MTO.S"},
{Name:"Metro Bank", BBTicker: "MTRO", OtasID: "OT.MTRO.S"},
{Name:"Murray International Trust", BBTicker: "MYI", OtasID: "OT.MYI.S"},
{Name:"NB Global Floating Rate Inc Fund £", BBTicker: "NBLS", OtasID: "OT.NBLS.S"},
{Name:"National Express Group", BBTicker: "NEX", OtasID: "OT.NEX.S"},
{Name:"National Grid", BBTicker: "NG", OtasID: "OT.NG.S"},
{Name:"NMC Health", BBTicker: "NMC", OtasID: "OT.NMC.S"},
{Name:"Nostrum Oil & Gas", BBTicker: "NOG", OtasID: "OT.NOG.S"},
{Name:"NewRiver Retail", BBTicker: "NRR", OtasID: "OT.NRR.S"},
{Name:"Northgate", BBTicker: "NTG", OtasID: "OT.NTG.S"},
{Name:"NEX Group", BBTicker: "NXG", OtasID: "OT.NXG.S"},
{Name:"Next", BBTicker: "NXT", OtasID: "OT.NXT.S"},
{Name:"Ocado Group", BBTicker: "OCDO", OtasID: "OT.OCDO.S"},
{Name:"Old Mutual Group", BBTicker: "OML", OtasID: "OT.OML.S"},
{Name:"Onesavings Bank", BBTicker: "OSB", OtasID: "OT.OSB.S"},
{Name:"P2P Global Investments", BBTicker: "PP", OtasID: "OT.PP.S"},
{Name:"Paragon Group of Companies The", BBTicker: "PAG", OtasID: "OT.PAG.S"},
{Name:"PageGroup", BBTicker: "PAGE", OtasID: "OT.PAGE.S"},
{Name:"PayPoint", BBTicker: "PAY", OtasID: "OT.PAY.S"},
{Name:"Paysafe Group", BBTicker: "PAYS", OtasID: "OT.PAYS.S"},
{Name:"Polar Capital Technology Trust", BBTicker: "PCT", OtasID: "OT.PCT.S"},
{Name:"Petra Diamonds", BBTicker: "PDL", OtasID: "OT.PDL.S"},
{Name:"Pets At Home Group", BBTicker: "PETS", OtasID: "OT.PETS.S"},
{Name:"Petrofac", BBTicker: "PFC", OtasID: "OT.PFC.S"},
{Name:"Provident Financial", BBTicker: "PFG", OtasID: "OT.PFG.S"},
{Name:"Phoenix Group Holdings", BBTicker: "PHNX", OtasID: "OT.PHNX.S"},
{Name:"Perpetual Income And Growth Investment Trust", BBTicker: "PLI", OtasID: "OT.PLI.S"},
{Name:"Polypipe Group", BBTicker: "PLP", OtasID: "OT.PLP.S"},
{Name:"Personal Assets Trust", BBTicker: "PNL", OtasID: "OT.PNL.S"},
{Name:"Pennon Group", BBTicker: "PNN", OtasID: "OT.PNN.S"},
{Name:"Polymetal International", BBTicker: "POLY", OtasID: "OT.POLY.S"},
{Name:"Paddy Power Betfair", BBTicker: "PPB", OtasID: "OT.PPB.S"},
{Name:"Prudential", BBTicker: "PRU", OtasID: "OT.PRU.S"},
{Name:"Pershing Square Holdings Ord Npv", BBTicker: "PSH", OtasID: "OT.PSH.S"},
{Name:"Persimmon", BBTicker: "PSN", OtasID: "OT.PSN.S"},
{Name:"Pearson", BBTicker: "PSON", OtasID: "OT.PSON.S"},
{Name:"Playtech", BBTicker: "PTEC", OtasID: "OT.PTEC.S"},
{Name:"PZ Cussons", BBTicker: "PZC", OtasID: "OT.PZC.S"},
{Name:"QinetiQ Group", BBTicker: "QQ", OtasID: "OT.QQ.S"},
{Name:"Rathbone Brothers", BBTicker: "RAT", OtasID: "OT.RAT.S"},
{Name:"Reckitt Benckiser Group", BBTicker: "RB", OtasID: "OT.RB.S"},
{Name:"Royal Bank of Scotland Group The", BBTicker: "RBS", OtasID: "OT.RBS.S"},
{Name:"RIT Capital Partners", BBTicker: "RCP", OtasID: "OT.RCP.S"},
{Name:"Redefine International", BBTicker: "RDI", OtasID: "OT.RDI.S"},
{Name:"Royal Dutch Shell", BBTicker: "RDSA", OtasID: "OT.RDSA.S"},
{Name:"Royal Dutch Shell", BBTicker: "RDSB", OtasID: "OT.RDSB.S"},
{Name:"Redrow", BBTicker: "RDW", OtasID: "OT.RDW.S"},
{Name:"RELX", BBTicker: "REL", OtasID: "OT.REL.S"},
{Name:"Rio Tinto", BBTicker: "RIO", OtasID: "OT.RIO.S"},
{Name:"Royal Mail", BBTicker: "RMG", OtasID: "OT.RMG.S"},
{Name:"Rightmove", BBTicker: "RMV", OtasID: "OT.RMV.S"},
{Name:"Rank Group The", BBTicker: "RNK", OtasID: "OT.RNK.S"},
{Name:"Rotork", BBTicker: "ROR", OtasID: "OT.ROR.S"},
{Name:"RPC Group", BBTicker: "RPC", OtasID: "OT.RPC.S"},
{Name:"Rolls-Royce Group", BBTicker: "RR", OtasID: "OT.RR.S"},
{Name:"Randgold Resources", BBTicker: "RRS", OtasID: "OT.RRS.S"},
{Name:"RSA Insurance Group", BBTicker: "RSA", OtasID: "OT.RSA.S"},
{Name:"Riverstone Energy Limited", BBTicker: "RSE", OtasID: "OT.RSE.S"},
{Name:"Renishaw", BBTicker: "RSW", OtasID: "OT.RSW.S"},
{Name:"Restaurant Group The", BBTicker: "RTN", OtasID: "OT.RTN.S"},
{Name:"Rentokil Initial", BBTicker: "RTO", OtasID: "OT.RTO.S"},
{Name:"Safestore Holdings", BBTicker: "SAFE", OtasID: "OT.SAFE.S"},
{Name:"Saga", BBTicker: "SAGA", OtasID: "OT.SAGA.S"},
{Name:"Sainsbury J", BBTicker: "SBRY", OtasID: "OT.SBRY.S"},
{Name:"Scottish Investment Trust the", BBTicker: "SCIN", OtasID: "OT.SCIN.S"},
{Name:"Softcat", BBTicker: "SCT", OtasID: "OT.SCT.S"},
{Name:"Schroders", BBTicker: "SDR", OtasID: "OT.SDR.S"},
{Name:"Stagecoach Group", BBTicker: "SGC", OtasID: "OT.SGC.S"},
{Name:"Sage Group The", BBTicker: "SGE", OtasID: "OT.SGE.S"},
{Name:"SuperGroup", BBTicker: "SGP", OtasID: "OT.SGP.S"},
{Name:"Segro", BBTicker: "SGRO", OtasID: "OT.SGRO.S"},
{Name:"Shaftesbury", BBTicker: "SHB", OtasID: "OT.SHB.S"},
{Name:"SIG", BBTicker: "SHI", OtasID: "OT.SHI.S"},
{Name:"Shire", BBTicker: "SHP", OtasID: "OT.SHP.S"},
{Name:"Smurfit Kappa Group", BBTicker: "SKG", OtasID: "OT.SKG.S"},
{Name:"Sky", BBTicker: "SKY", OtasID: "OT.SKY.S"},
{Name:"STANDARD LIFE PLC ORD 12 2/9P", BBTicker: "SLA", OtasID: "OT.SLA.S"},
{Name:"Smith DS", BBTicker: "SMDS", OtasID: "OT.SMDS.S"},
{Name:"Smiths Group", BBTicker: "SMIN", OtasID: "OT.SMIN.S"},
{Name:"St Modwen Properties", BBTicker: "SMP", OtasID: "OT.SMP.S"},
{Name:"Scottish Mortgage Investment Trust", BBTicker: "SMT", OtasID: "OT.SMT.S"},
{Name:"WH Smith", BBTicker: "SMWH", OtasID: "OT.SMWH.S"},
{Name:"Smith & Nephew", BBTicker: "SN", OtasID: "OT.SN.S"},
{Name:"Sanne Group", BBTicker: "SNN", OtasID: "OT.SNN.S"},
{Name:"Senior", BBTicker: "SNR", OtasID: "OT.SNR.S"},
{Name:"Sophos Group", BBTicker: "SOPH", OtasID: "OT.SOPH.S"},
{Name:"Sports Direct International", BBTicker: "SPD", OtasID: "OT.SPD.S"},
{Name:"Spire Healthcare Group", BBTicker: "SPI", OtasID: "OT.SPI.S"},
{Name:"Spirax-Sarco Engineering", BBTicker: "SPX", OtasID: "OT.SPX.S"},
{Name:"Serco Group", BBTicker: "SRP", OtasID: "OT.SRP.S"},
{Name:"SSE", BBTicker: "SSE", OtasID: "OT.SSE.S"},
{Name:"SSP Group", BBTicker: "SSPG", OtasID: "OT.SSPG.S"},
{Name:"Standard Chartered", BBTicker: "STAN", OtasID: "OT.STAN.S"},
{Name:"St James's Place", BBTicker: "STJ", OtasID: "OT.STJ.S"},
{Name:"Stobart Group", BBTicker: "STOB", OtasID: "OT.STOB.S"},
{Name:"Savills", BBTicker: "SVS", OtasID: "OT.SVS.S"},
{Name:"Severn Trent", BBTicker: "SVT", OtasID: "OT.SVT.S"},
{Name:"Spectris", BBTicker: "SXS", OtasID: "OT.SXS.S"},
{Name:"Sirius Minerals", BBTicker: "SXX", OtasID: "OT.SXX.S"},
{Name:"Synchronica", BBTicker: "SYNC", OtasID: "OT.SYNC.S"},
{Name:"Synthomer", BBTicker: "SYNT", OtasID: "OT.SYNT.S"},
{Name:"TalkTalk Telecom Group", BBTicker: "TALK", OtasID: "OT.TALK.S"},
{Name:"Tate & Lyle", BBTicker: "TATE", OtasID: "OT.TATE.S"},
{Name:"TBC Bank Group", BBTicker: "TBCG", OtasID: "OT.TBCG.S"},
{Name:"TP Icap", BBTicker: "TCAP", OtasID: "OT.TCAP.S"},
{Name:"Thomas Cook Group", BBTicker: "TCG", OtasID: "OT.TCG.S"},
{Name:"Ted Baker", BBTicker: "TED", OtasID: "OT.TED.S"},
{Name:"Templeton Emerging Markets Investment Trust", BBTicker: "TEM", OtasID: "OT.TEM.S"},
{Name:"Telecom plus", BBTicker: "TEP", OtasID: "OT.TEP.S"},
{Name:"Tullow Oil", BBTicker: "TLW", OtasID: "OT.TLW.S"},
{Name:"Temple Bar Investment Trust", BBTicker: "TMPL", OtasID: "OT.TMPL.S"},
{Name:"Travis Perkins", BBTicker: "TPK", OtasID: "OT.TPK.S"},
{Name:"The Renewables Infrastructure Group", BBTicker: "TRIG", OtasID: "OT.TRIG.S"},
{Name:"TR Property Investment Trust", BBTicker: "TRY", OtasID: "OT.TRY.S"},
{Name:"Tesco", BBTicker: "TSCO", OtasID: "OT.TSCO.S"},
{Name:"TUI AG", BBTicker: "TUI", OtasID: "OT.TUI.S"},
{Name:"Taylor Wimpey", BBTicker: "TW", OtasID: "OT.TW.S"},
{Name:"UBM", BBTicker: "UBM", OtasID: "OT.UBM.S"},
{Name:"UDG Healthcare", BBTicker: "UDG", OtasID: "OT.UDG.S"},
{Name:"UK Commercial Property Trust", BBTicker: "UKCM", OtasID: "OT.UKCM.S"},
{Name:"Ultra Electronics Holdings", BBTicker: "ULE", OtasID: "OT.ULE.S"},
{Name:"Unilever", BBTicker: "ULVR", OtasID: "OT.ULVR.S"},
{Name:"Unite Group", BBTicker: "UTG", OtasID: "OT.UTG.S"},
{Name:"United Utilities Group", BBTicker: "UU", OtasID: "OT.UU.S"},
{Name:"Victrex", BBTicker: "VCT", OtasID: "OT.VCT.S"},
{Name:"Vectura Group", BBTicker: "VEC", OtasID: "OT.VEC.S"},
{Name:"Vedanta Resources", BBTicker: "VED", OtasID: "OT.VED.S"},
{Name:"Vietnam Enterprise Investments", BBTicker: "VEIL", OtasID: "OT.VEIL.S"},
{Name:"Virgin Money Holdings UK", BBTicker: "VM", OtasID: "OT.VM.S"},
{Name:"Vodafone Group", BBTicker: "VOD", OtasID: "OT.VOD.S"},
{Name:"Vesuvius", BBTicker: "VSVS", OtasID: "OT.VSVS.S"},
{Name:"Weir Group", BBTicker: "WEIR", OtasID: "OT.WEIR.S"},
{Name:"John Wood Group", BBTicker: "WG", OtasID: "OT.WG.S"},
{Name:"Wizz Air Holdings", BBTicker: "WIZZ", OtasID: "OT.WIZZ.S"},
{Name:"Workspace Group", BBTicker: "WKP", OtasID: "OT.WKP.S"},
{Name:"William Hill", BBTicker: "WMH", OtasID: "OT.WMH.S"},
{Name:"Woodford Patient Capital Trust", BBTicker: "WPCT", OtasID: "OT.WPCT.S"},
{Name:"Worldpay Group", BBTicker: "WPG", OtasID: "OT.WPG.S"},
{Name:"WPP Group", BBTicker: "WPP", OtasID: "OT.WPP.S"},
{Name:"Witan Investment Trust", BBTicker: "WTAN", OtasID: "OT.WTAN.S"},
{Name:"Whitbread", BBTicker: "WTB", OtasID: "OT.WTB.S"},
{Name:"Worldwide Healthcare Trust", BBTicker: "WWH", OtasID: "OT.WWH.S"},
{Name:"Zoopla Property Group", BBTicker: "ZPG", OtasID: "OT.ZPG.S"}

];
